### ISSUE TITLE
Place with same opening hours does not get "same" as value

### ISSUE THREAD

**Issue by datendelphin** [osmontrouge/caresteouvert#259] opened 2020-04-08 21:24 UTC
**Describe the bug**
When I confirm that the place has the same opening hours as usual, a copy of the opening hours is added instead of opening_hours:covid19=same

**To Reproduce**
1. Go to 'Report a change' for a POI with normal opening hours
2. Click on 'yes'
3. Click on 'same hours'
4. Confirm

**Expected behavior**
Tag opening_hours:covid19=same is added

**Additional context**
https://github.com/bleibtoffen/caresteouvert-de/issues/41
https://www.openstreetmap.org/node/958154999

**Comment by PanierAvide** [comment] 2020-04-09 06:40
Thanks for reporting this. It is intended behaviour, as `same` value was at start mistakenly used for either a shop which is open with same opening hours, or shop open during lockdown but with unknown usual opening hours (which corresponds now to `open` value). To keep things clear, when hours are identical, we copy hours to make sure they are identical.

**Comment by caugner** [comment] 2020-04-09 10:50
@PanierAvide In this case, the value seems to have not been copied correctly:
https://www.openstreetmap.org/way/609946515

**Comment by PanierAvide** [comment] 2020-04-09 10:53
Are you sure this was copied, and not an user who did the input directly through our form ?

**Comment by caugner** [comment] 2020-04-09 10:54
> Are you sure this was copied, and not an user who did the input directly through our form ?

Pretty sure:
![grafik](https://user-images.githubusercontent.com/495429/78888001-29cdf000-7a61-11ea-8bf4-f49c2f3951f6.png)

> It is intended behaviour, as same value was at start mistakenly used for ...

Is there already an open issue to migrate the old data from `same` to `open`?

**Comment by PanierAvide** [comment] 2020-04-09 11:03
Sure, but I mean if user defines opening hours through assisted form, and without setting any details in last text field, it will be directly edited in OSM.

No issue yet to migrate same values to open, however we don't create new values on our side since last week.

**Comment by caugner** [comment] 2020-04-09 11:18
> https://github.com/osmontrouge/caresteouvert/issues/259#issuecomment-611463425

This looks like the original value was parsed incompletely, because the specific holidays are not yet supported (by the frontend or the worker, not sure).

**Comment by datendelphin** [comment] 2020-04-09 19:28
I did that edit. After clicking "same hours", the editor pops up. I didn't do any changes and just clicked continue.
I would prefer the value "same" in OSM despite the initial problem, because OSM contributors will inevitably use "same" as well. But I understand now where this comes from.

**Comment by caugner** [comment] 2020-04-10 18:46
> No issue yet to migrate same values to open, however we don't create new values on our side since last week.

I have created on now: https://github.com/osmontrouge/caresteouvert/issues/300

**Comment by PanierAvide** [comment] 2020-04-11 06:49
Closing this one as discussion follow in #300

**Closed by PanierAvide** 2020-04-11 06:49 UTC
Labels: question
